Repository FitTheMan/ftm-server, pull requests merged in 2025-03, with the labels that each got.

#12 chore: develop pull request, develop build deploy 워크플로 환경 변수 설정 스텝 수정
  .github/workflows/develop_build_deploy.yml
  .github/workflows/develop_pull_request.yml
  src/test/java/com/ftm/server/ServerApplicationTests.java
Labels: ⚙️ chore

#18 feat: Redis 설정 및 세팅 작업(#16)
  src/main/java/com/ftm/server/adapter/gateway/.gitkeep
  src/main/java/com/ftm/server/adapter/gateway/RedisCacheGateway.java
  src/main/java/com/ftm/server/adapter/gateway/RedisSessionGateway.java
  src/main/java/com/ftm/server/adapter/gateway/repository/.gitkeep
  src/main/java/com/ftm/server/infrastructure/redis/.gitkeep
  src/main/java/com/ftm/server/infrastructure/redis/RedisConfig.java
  src/main/java/com/ftm/server/infrastructure/redis/RedisProperties.java
  src/main/java/com/ftm/server/infrastructure/redis/RedisService.java
  src/main/resources/application.yml
Labels: ⚡ feature

#20 refactor: 테스트 환경 db 변경과 설정 및 세팅 수정
  .github/workflows/develop_build_deploy.yml
  .github/workflows/develop_pull_request.yml
  .gitignore
  build.gradle
  docker-compose-test.yml
  src/main/resources/logback-spring.xml
  src/test/java/com/ftm/server/ServerApplicationTests.java
  src/test/resources/application-test.yml
Labels: 🚀 refactor

#27 feat: 시큐리티 기본 설정 및 핸들러 구성
  build.gradle
  src/main/java/com/ftm/server/infrastructure/security/.gitkeep
  src/main/java/com/ftm/server/infrastructure/security/SecurityConfig.java
  src/main/java/com/ftm/server/infrastructure/security/handler/PermissionDeniedHandler.java
  src/main/java/com/ftm/server/infrastructure/security/handler/SecurityResponseHandler.java
  src/main/java/com/ftm/server/infrastructure/security/handler/UnauthenticatedAccessHandler.java
  src/main/resources/application-security.yml
Labels: ⚡ feature

#28 chore: cicd 환경 스키마, 데이터 init 및 문서화 작업 step 추가
  .github/workflows/develop_build_deploy.yml
  .github/workflows/develop_pull_request.yml
Labels: ⚙️ chore

#30 fix: 베포 워크플로에서 asciidoctor snippet 경로를 인식하지 못하는 에러 해결
  build.gradle
Labels: 🔴 bug/error

#34 feat: UseCase, Infrastructure 계층 커스텀 어노테이션 추가
  gradlew
  src/main/java/com/ftm/server/common/annotation/InfraService.java
  src/main/java/com/ftm/server/common/annotation/UseCase.java
  src/main/java/com/ftm/server/infrastructure/redis/RedisService.java
Labels: ⚡ feature

#51 refactor: 유저 이미지 조회 쿼리 예외처리 변경
  src/main/java/com/ftm/server/common/response/enums/ErrorResponseCode.java
  src/main/java/com/ftm/server/domain/service/UserImageService.java
Labels: 🚀 refactor

#53 feat : Add General User SigunUp API(#48)
  src/docs/asciidoc/index.adoc
  src/main/java/com/ftm/server/adapter/controller/user/GeneralUserSignupController.java
  src/main/java/com/ftm/server/adapter/controller/user/GetUserSignupOptionsController.java
  src/main/java/com/ftm/server/adapter/dto/request/GeneralUserSignupRequest.java
  src/main/java/com/ftm/server/adapter/dto/response/UserSignupOptionsResponse.java
  src/main/java/com/ftm/server/adapter/gateway/AuthenticationGateway.java
  src/main/java/com/ftm/server/adapter/gateway/repository/EmailVerificationLogsRepository.java
  src/main/java/com/ftm/server/common/response/enums/ErrorResponseCode.java
  src/main/java/com/ftm/server/common/utils/RandomNickNameCreator.java
  src/main/java/com/ftm/server/domain/dto/command/GeneralUserCreationCommand.java
  src/main/java/com/ftm/server/domain/dto/command/GeneralUserSignupCommand.java
  src/main/java/com/ftm/server/domain/dto/query/FindEmailVerificationLogsByEmailQuery.java
  src/main/java/com/ftm/server/domain/dto/vo/UserSignupOptionsVo.java
  src/main/java/com/ftm/server/domain/service/EmailVerificationLogsService.java
  src/main/java/com/ftm/server/domain/service/UserImageService.java
  src/main/java/com/ftm/server/domain/service/UserService.java
  src/main/java/com/ftm/server/domain/usecase/user/GeneralUserSignupUseCase.java
  src/main/java/com/ftm/server/domain/usecase/user/GetUserSignupOptionsUseCase.java
  src/main/java/com/ftm/server/entity/entities/User.java
  src/main/java/com/ftm/server/entity/entities/UserImage.java
  src/main/java/com/ftm/server/infrastructure/security/AuthenticationService.java
  src/main/java/com/ftm/server/infrastructure/security/SecurityConfig.java
  src/test/java/com/ftm/server/user/GeneralUserSignupTest.java
  src/test/java/com/ftm/server/user/GetUserSignupOptionsTest.java
Labels: ⚡ feature

#56 chore: gradle asciidoc 설정 변경
  build.gradle
  src/docs/asciidoc/auth-api.adoc
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/user-api.adoc
Labels: 📄 documentation, ⚙️ chore

#58 chore: cors 허용 경로에 클라이언트 로컬 환경 경로 추가
  src/main/java/com/ftm/server/infrastructure/security/SecurityConfig.java
Labels: ⚙️ chore

#64 feat : Add Social User Signup API(#61)
  src/docs/asciidoc/user-api.adoc
  src/main/java/com/ftm/server/application/dto/command/GeneralUserCreationCommand.java
  src/main/java/com/ftm/server/application/dto/command/SocialUserCreationCommand.java
  src/main/java/com/ftm/server/application/dto/command/SocialUserSignupCommand.java
  src/main/java/com/ftm/server/application/dto/query/FindBySocialValueQuery.java
  src/main/java/com/ftm/server/application/port/repository/UserRepository.java
  src/main/java/com/ftm/server/application/service/UserImageService.java
  src/main/java/com/ftm/server/application/service/UserService.java
  src/main/java/com/ftm/server/application/usecase/user/EmailAuthenticationUseCase.java
  src/main/java/com/ftm/server/application/usecase/user/GeneralUserSignupUseCase.java
  src/main/java/com/ftm/server/application/usecase/user/SocialUserSignupUseCase.java
  src/main/java/com/ftm/server/common/consts/PropertiesHolder.java
  src/main/java/com/ftm/server/common/response/enums/ErrorResponseCode.java
  src/main/java/com/ftm/server/domain/entity/User.java
  src/main/java/com/ftm/server/domain/vo/SocialUserSignupSummaryVo.java
  src/main/java/com/ftm/server/domain/vo/UserSummaryVo.java
  src/main/java/com/ftm/server/infrastructure/security/SecurityConfig.java
  src/main/java/com/ftm/server/web/controller/user/SocialUserSignupController.java
  src/main/java/com/ftm/server/web/dto/request/GeneralUserSignupRequest.java
  src/main/java/com/ftm/server/web/dto/request/SocialUserSignupRequest.java
  src/main/java/com/ftm/server/web/dto/response/SocialUserSignupResponse.java
  src/test/java/com/ftm/server/auth/UserLoginTest.java
  src/test/java/com/ftm/server/user/GeneralUserSignupTest.java
  src/test/java/com/ftm/server/user/SocialUserSignupTest.java
Labels: ⚡ feature

#66 docs : Add Response Header To API Documentation(#61)
  src/docs/asciidoc/user-api.adoc
  src/test/java/com/ftm/server/user/SocialUserSignupTest.java
Labels: 📄 documentation

#68 chore: cors 경로에 https 로컬 클라이언트 경로 추가
  src/main/java/com/ftm/server/infrastructure/security/SecurityConfig.java
Labels: ⚙️ chore

#70 fix: 개발환경 세션 쿠키 cross-site 요청 이슈 해결
  src/main/resources/application-dev.yml
Labels: 🔴 bug/error

#72 chore: 개발 환경에서 세션 쿠키 도메인 설정, CORS 허용 메소드 추가
  src/main/java/com/ftm/server/infrastructure/security/SecurityConfig.java
  src/main/resources/application-dev.yml
Labels: ⚙️ chore
